# Generated by Django 5.0.1 on 2024-01-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_18", "Under 18"),
                    ("18_24", "18-24"),
                    ("25_34", "25-34"),
                    ("35_44", "35-44"),
                    ("45_54", "45-54"),
                    ("55_plus", "55+"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("non_binary", "Non-Binary"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="movies_per_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0_1", "0 - 1"),
                    ("2_4", "2 - 4"),
                    ("5_7", "5 - 7"),
                    ("8_10", "8 - 10"),
                    ("11_15", "11 - 15"),
                    ("16_plus", "16+"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
