# Generated by Django 5.0.1 on 2024-01-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emotions", "0002_user_age_group_user_gender_user_movies_per_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="last login"),
        ),
    ]
